/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ranked chains matching a query — the selection candidates. */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build a timeline spec from a chosen set of chains.
         * @description Seconds for a large selection: it recovers HTML from host messages and detects boilerplate across the whole set.
         */
        post: operations["buildSpec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entries/{extId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One entry with its provenance. */
        get: operations["getEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chains/{rootExtId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A chain's entries in time order. */
        get: operations["getChain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Corpus overview. */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everyone in the corpus, most-involved first. */
        get: operations["getPeople"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        SearchResult: {
            chains?: components["schemas"]["ChainHit"][];
            entries?: components["schemas"]["EntryHit"][];
        };
        /** @description A conversation, ranked by the aggregate relevance of its entries. */
        ChainHit: {
            /** @description The chain's durable name, and the id a selection is made of. */
            rootExtId: string;
            subject?: string;
            container?: string;
            sources?: string[];
            /** @description Size of the whole chain. */
            entries: number;
            /** @description How much of the chain the query hit. */
            matched: number;
            first?: string;
            last?: string;
            score?: number;
            best?: components["schemas"]["EntryHit"][];
        };
        EntryHit: {
            extId: string;
            source?: string;
            ts?: string;
            person?: string;
            container?: string;
            subject?: string;
            permalink?: string;
            /** @description FTS excerpt, matched terms wrapped in [ ]. */
            snippet?: string;
            score?: number;
            proseRank?: number;
            identRank?: number;
            semRank?: number;
            similarity?: number;
        };
        SpecRequest: {
            /** @description Chain root ext ids, as chosen by a person. */
            chains: string[];
            title?: string;
            me?: string;
        };
        Stats: {
            entries?: number;
            bySource?: {
                [key: string]: number;
            };
            unresolved?: number;
            roots?: number;
            people?: number;
        };
        Person: {
            personId?: number;
            displayName?: string;
            identities?: string[];
            sent?: number;
            received?: number;
        };
    };
    responses: {
        /** @description The service declined, and says why. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search: {
        parameters: {
            query?: {
                q?: string;
                person?: string;
                /** @description ISO date; entries older than this are excluded. */
                since?: string;
                /** @description semantic and hybrid need the embedding daemon; a search asking for either fails with 503 when it is not running. */
                mode?: "lexical" | "semantic" | "hybrid";
                limit?: number;
                /** @description Also return the matching entries, not only their chains. */
                entries?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked results, best first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            400: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    buildSpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecRequest"];
            };
        };
        responses: {
            /** @description A timeline spec. Left unmodelled on purpose — the spec's shape is generated from schema/timeline.schema.json into src/lib/spec.d.ts, and a second declaration of it here would be a second source of truth. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                extId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The entry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryHit"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getChain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rootExtId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The chain's entries, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        rootExtId: string;
                        subject?: string;
                        entries: components["schemas"]["EntryHit"][];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Counts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    getPeople: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description People. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"][];
                };
            };
        };
    };
}
