/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ranked chains for a query — the selection candidates.
         * @description Selection stage. Lexical by default: FTS5 wins decisively on the tokens a mail corpus is dense with (invoice numbers, account ids, Message-IDs), and the structural half of a real question is a filter rather than something a similarity score encodes.
         *
         *     At least one of q, person or since must be given. With no filter at all an arbitrary slice of the corpus would come back reading like a ranked answer, so that is a 400.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build a timeline spec from a chosen set of chains.
         * @description Render stage, and deliberately separate from search: what belongs on a page is a human decision, and removing a thread afterwards means regenerating everything downstream, so scope is settled once, up front.
         *
         *     The response validates against schema/timeline.schema.json, the contract the renderer already consumes.
         *
         *     Expensive: spec assembly recovers quoted bodies, detects repeated boilerplate and builds attachment thumbnails, which is seconds for a large selection. There is no job queue — the response is synchronous. Concurrency is capped, so an over-eager caller gets 429 rather than a server with every core in HTML recovery.
         *
         *     Entry bodies are sender HTML, and it is NOT sanitised (issue #14). That is accepted at today's risk because the server binds to loopback only. It is a hard blocker on binding wider, not a footnote.
         */
        post: operations["buildSpec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/specs/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A page that POST /v1/spec saved under a name — the read half of the render route /view/<name>.
         * @description The page was written by the same server process family (specs live beside the corpus, in ~/.local/state/chainmail/specs), so a refresh or a reboot lands back on the same page from the same URL. The response is byte-identical to what the build returned.
         */
        get: operations["getSavedSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entries/{extId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One entry, with its provenance and every sighting of it. */
        get: operations["getEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chains/{rootExtId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The chain around an entry, in time order, as data.
         * @description Kept even though selection makes it unnecessary for building a page, because reading a chain is a different act from rendering one: a client browsing a candidate wants its entries as data, cheaply, without paying for spec assembly or committing to a page.
         *
         *     Reachability is followed in BOTH directions, so ANY member's ext id returns the whole conversation — search reports the entry that matched, not the root. The parameter is named rootExtId because that is what search hands you.
         */
        get: operations["getChain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counts and coverage. */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everyone in the corpus, with their identities. */
        get: operations["getPeople"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bring a previously built page up to date.
         * @description Refresh stage, and deliberately the read half of the CLI's `refresh` command. The caller posts the previous spec (as POST /v1/spec returned it) and any selection overrides; the server re-derives the page from the corpus — a chain already on the page that gained entries is grown, a new chain the recorded queries find is proposed rather than included — and returns the regenerated spec alongside a report of what changed.
         *
         *     The server never reaches the mailbox, on purpose: fetching what arrived is `corpus ingest`'s job and belongs to the CLI and the cron, not a browser. So this refresh is corpus-only. What it cannot see, it cannot propose from fed to it by the mailbox later.
         */
        post: operations["refreshSpec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Ranked candidates. Exactly one of chains or entries is present, decided by the `entries` parameter; neither is present when nothing matched, and an empty array is returned rather than omitted in that case. */
        SearchResponse: {
            /**
             * @description The retrieval mode actually used.
             * @enum {string}
             */
            mode: "lexical" | "semantic" | "hybrid";
            /** @description Present when entries=false (the default). */
            chains?: components["schemas"]["ChainHit"][];
            /** @description Present when entries=true. */
            entries?: components["schemas"]["EntryHit"][];
        };
        /** @description One candidate chain — the unit a caller selects for POST /v1/spec. */
        ChainHit: {
            /**
             * @description Ext id of the entry the reply graph terminates at. The only chain identity worth storing, and what POST /v1/spec takes.
             * @example mail:<c0ffee-1@example.com>
             */
            rootExtId: string;
            /** @description Subject of the chain. Absent when no entry in it carries one. */
            subject?: string;
            /** @description Mail thread id or Slack channel id. Absent when the source stated none. */
            container?: string;
            /** @description Every archive this chain has entries from; more than one where a mail trail continued in Slack. */
            sources?: ("mail" | "slack")[];
            /** @description Entries in the whole chain. */
            entries: number;
            /** @description How many of them the query hit. matched/entries is the honest measure of whether the chain is about the query. */
            matched: number;
            /**
             * Format: date-time
             * @description Timestamp of the earliest entry, UTC.
             */
            first: string;
            /**
             * Format: date-time
             * @description Timestamp of the latest entry, UTC.
             */
            last: string;
            /** @description Fused score. Comparable within one response only. */
            score: number;
            /** @description The top-scoring entries of this chain, most relevant first — the evidence for the ranking. */
            best?: components["schemas"]["EntryHit"][];
        };
        /** @description One matching entry, as ranking sees it. */
        EntryHit: {
            /**
             * @description Corpus natural key, e.g. "mail:<c0ffee-1@example.com>". The identity that survives a rebuild, and the one the other endpoints take.
             * @example mail:<c0ffee-1@example.com>
             */
            extId: string;
            /**
             * @description Which archive it came from.
             * @enum {string}
             */
            source: "mail" | "slack";
            /**
             * Format: date-time
             * @description Entry timestamp, UTC.
             */
            ts: string;
            /** @description Author's person id, 0 when the author could not be resolved. */
            personId: number;
            /** @description Author's display name. Absent when no person row is attached. */
            person?: string;
            /** @description Mail thread id or Slack channel id. Absent when the source stated none. */
            container?: string;
            /** @description Absent for sources that have no subject, such as Slack. */
            subject?: string;
            /** @description Opens the entry at its source. Absent when the source gave none. */
            permalink?: string;
            /** @description Match excerpt with matched terms wrapped in square brackets. Absent for a structural-only query, which has nothing to highlight. */
            snippet?: string;
            /** @description Fused Reciprocal Rank Fusion score. Comparable within one response only. */
            score: number;
            /** @description 1-based position in the prose ranking; 0 means that ranking did not find this entry. Always present, because 0 is meaningful. */
            proseRank: number;
            /** @description 1-based position in the identifier (trigram) ranking; 0 means it did not find this entry. */
            identRank: number;
            /** @description 1-based position in the vector ranking; 0 means it did not find this entry, and is always 0 for mode=lexical. */
            semRank: number;
            /** @description Cosine to the query vector, in [-1, 1]. Present only when semRank is non-zero; it is reported, not fused. */
            similarity?: number;
        };
        /** @description One entry resolved for reading rather than for ranking: plain text, with its provenance. Deliberately not a timeline entry — no HTML recovery, no boilerplate folding, no thumbnails — so reading a chain costs a query rather than seconds of assembly. Use POST /v1/spec when the goal is to render. */
        CorpusEntry: {
            /**
             * @description Corpus natural key.
             * @example mail:<c0ffee-1@example.com>
             */
            extId: string;
            /**
             * @description Which archive it came from.
             * @enum {string}
             */
            source: "mail" | "slack";
            /** @description True when this entry exists only because someone quoted it: it was never in the mailbox as a standalone message. */
            quoted: boolean;
            /**
             * Format: date-time
             * @description Entry timestamp, UTC.
             */
            ts: string;
            /** @description Zone label as the source stated it, e.g. "NZST". Absent when the source stated none; never guessed here. */
            tz?: string;
            /** @description Minutes east of UTC as the source stated it. Absent when it stated none. Carried alongside tz because a label does not determine an offset. */
            tzOffsetMinutes?: number;
            /** @description Display name of the sender. Absent when no person row is attached. */
            author?: string;
            /** @description Absent for sources that have no subject. */
            subject?: string;
            /** @description The entry's own plain text. Absent when the source carried no text body. */
            body?: string;
            /** @description Mail thread id or Slack channel id. Absent when the source stated none. */
            container?: string;
            /** @description Opens the entry at its source. Absent when the source gave none. */
            permalink?: string;
            /** @description Ext id of the entry this replies to. Absent at a chain root, and also absent when it names a parent that is not in the corpus — parentRef tells the two apart. */
            parent?: string;
            /** @description What the entry names as its parent (a Message-ID or thread_ts), resolved or not. Present with no parent means a known hole. */
            parentRef?: string;
            /** @description Every place this entry was found. */
            sightings?: components["schemas"]["Sighting"][];
            /** @description Everyone recorded on it, senders first. */
            participants?: components["schemas"]["Participant"][];
        };
        /** @description Every entry reachable from the named one, in time order. */
        ChainResponse: {
            /** @description The id that was asked for, echoed back. Note this is whatever the caller passed, which need not be the chain's root — see the path parameter. */
            rootExtId: string;
            /** @description The whole chain in time order, never empty: an id that resolves to nothing is a 404. */
            entries: components["schemas"]["CorpusEntry"][];
        };
        /** @description One place an entry was found. A message quoted in five forwards has five, which is the evidence that it mattered. */
        Sighting: {
            /**
             * @description How it was seen.
             * @enum {string}
             */
            kind: "direct" | "quoted" | "forwarded";
            /** @description Ext id of the message it was found inside. Absent for a direct sighting, which was not found inside anything. */
            seenIn?: string;
            /** @description Free-text note about the sighting. Absent when none was recorded. */
            detail?: string;
        };
        /** @description Someone recorded on an entry, in role order. */
        Participant: {
            /** @description Person id. */
            personId: number;
            /** @description Display name. */
            name: string;
            /**
             * @description How they appear on this entry.
             * @enum {string}
             */
            role: "from" | "to" | "cc";
        };
        /** @description A page built from a chosen set of chains. Selection is the caller's decision and is not re-derived from a query here: naming chains IS the selection step. */
        SpecRequest: {
            /**
             * @description Chain roots to include, as GET /v1/search reports them. At least one; an empty list is a 400, because a page with no messages fails the timeline schema.
             * @example [
             *       "mail:<c0ffee-1@example.com>",
             *       "mail:<c0ffee-2@example.com>"
             *     ]
             */
            chains: string[];
            /**
             * @description Page title. Defaults to the subject of the earliest selected entry, which the timeline schema requires to be non-empty.
             * @example Solar install quote
             */
            title?: string;
            /**
             * @description The reader's own addresses, so their outbound messages are marked. Nothing in the corpus knows which mailbox it was collected from.
             * @example [
             *       "me@example.fed"
             *     ]
             */
            me?: string[];
            /** @description The searches the selection came from, recorded on the page so that a hole in the timeline is interpretable. Purely descriptive: nothing is re-run. */
            queries?: components["schemas"]["SpecQuery"][];
            /**
             * @description When set, saves the built page under /view/<name> so it survives a refresh (and a reboot) and can be reopened from its URL. The client chooses it; the server validates it. Letters, digits, '.', '_', '-'; no slashes and no '..'. Blank builds without saving.
             * @example solar-install-quote
             */
            name?: string;
        };
        /** @description A search that was run, recorded for provenance. */
        SpecQuery: {
            /**
             * @description The query text.
             * @example solar install quote
             */
            q: string;
            /** @description Where it was run, e.g. "corpus search". */
            note?: string;
        };
        /** @description What is in the corpus, and what is missing. */
        Stats: {
            /** @description Total entries. */
            entries: number;
            /** @description Entry count per source. */
            bySource: {
                [key: string]: number;
            };
            /** @description Distinct people, senders and recipients alike. */
            people: number;
            /** @description Entries that open a chain: no parent, and none named. */
            chainRoots: number;
            /** @description Entries that name a parent which is not in the corpus. Known holes, not errors. */
            unresolved: number;
            /** @description Empty when nothing has been embedded, in which case mode=semantic and mode=hybrid have nothing to rank against. */
            embeddings: components["schemas"]["EmbedModelStats"][];
        };
        /** @description Embedding coverage for one model. Reported per model because a half-finished model migration is a real state, and from the results alone it looks like a corpus that lost recall. */
        EmbedModelStats: {
            /**
             * @description Model name.
             * @example nomic-embed-text
             */
            model: string;
            /** @description Dimensions its vectors have. */
            dim: number;
            /** @description Entries with a stored vector. */
            vectors: number;
            /** @description Entries deliberately not embedded, as having no topic. */
            skipped: number;
            /** @description Stored, but the entry's text or the preparation has moved on since. */
            stale: number;
            /** @description Entries a full backfill would still embed — how much work is left. */
            eligible: number;
        };
        /** @description Everyone in the corpus, most involved first. */
        PeopleResponse: {
            /** @description Most-involved first. */
            people: components["schemas"]["PersonSummary"][];
        };
        /** @description One person, with every identity that resolves to them. */
        PersonSummary: {
            /** @description Person id. */
            personId: number;
            /**
             * @description Best known display name.
             * @example Ada Okoye
             */
            displayName: string;
            /** @description Every address or uid folded into this person. */
            identities?: string[];
            /** @description Entries they authored. */
            sent: number;
            /** @description Entries they were a to: or cc: on. Sent 0 with received above 0 is a recipient-only participant, which is a quarter of a real cast. */
            received: number;
        };
        /** @description The previous run being brought up to date. The spec itself is authoritative for what stays on the page; the other fields narrow or rename how that membership is reproduced, and accept takes proposed chains the report returns. */
        RefreshRequest: {
            /** @description The previous spec, as POST /v1/spec returned it. Must carry at least one message; a fresh page has nothing to refresh. */
            spec: components["schemas"]["TimelineSpec"];
            /** @description Page title, overriding the spec's. */
            title?: string;
            /** @description Address, name or slack uid, overriding the spec's recorded selection. */
            person?: string;
            /**
             * Format: date
             * @description YYYY-MM-DD floor on entry dates, overriding the spec's recorded selection.
             */
            since?: string;
            /** @description How many chains a query may propose, overriding the spec's recorded selection. */
            limit?: number;
            /**
             * @description The reader's own addresses, so their outbound messages are marked.
             * @example [
             *       "me@example.fed"
             *     ]
             */
            me?: string[];
            /** @description Accept every chain the queries propose, without naming them one by one. Defaults to false: a curated page is not re-widened on every refresh. */
            includeNew?: boolean;
            /**
             * @description Chain roots to accept, as the report's chainsProposed names them. Accepting is idempotent: a chain accepted once is not proposed again.
             * @example [
             *       "mail:<c0ffee-1@loomworks.example>"
             *     ]
             */
            accept?: string[];
        };
        /** @description The regenerated spec, plus a report of what the refresh did to get there. The spec is what a client renders; the report is what it shows to explain a change. */
        RefreshResponse: {
            spec: components["schemas"]["TimelineSpec"];
            report: components["schemas"]["RefreshReport"];
        };
        /** @description What moved between the previous run and this one. A chain is in exactly one list: added (new to the page), grown (was there and gained entries), proposed (found but not accepted) or unranked (kept, but its query no longer finds it). */
        RefreshReport: {
            /** @description Messages on the page when the refresh started. */
            entriesBefore: number;
            /** @description Messages on the page after the refresh. */
            entriesAfter: number;
            /** @description Chains now on the page that were not on it before. Absent when none. */
            chainsAdded?: components["schemas"]["ChainGrowth"][];
            /** @description Chains on the page before that gained entries. Absent when none. */
            chainsGrown?: components["schemas"]["ChainGrowth"][];
            /** @description Chains a recorded query found that the page does not include, awaiting a decision. Accept them with the next refresh's accept. */
            chainsProposed?: components["schemas"]["RefreshCandidate"][];
            /** @description Chains still on the page that no recorded query returns anymore. They are kept — dropping one would delete entries somebody has already read. */
            chainsUnranked?: string[];
            /** @description The refresh looked and found nothing to store, grow, add or propose. Distinct from an error: a report existing at all means the refresh actually ran. */
            nothingNew: boolean;
        };
        /** @description One chain whose membership changed. before is absent when the chain is new to the page; after is what the page now holds. */
        ChainGrowth: {
            /** @description The chain's container id (a Gmail thread id or Slack channel id). */
            id: string;
            /** @description Subject of the chain, when it carries one. */
            subject?: string;
            /** @description Entries the chain had before. Absent when it is new to the page. */
            before?: number;
            /** @description Entries the chain holds now. */
            after: number;
        };
        /** @description A chain the queries found that the page does not yet include, named by the id that accepts it. */
        RefreshCandidate: {
            /**
             * @description The chain root to pass back as accept, as GET /v1/search reports it.
             * @example mail:<c0ffee-1@loomworks.example>
             */
            rootExtId: string;
            /** @description Subject of the chain, when it carries one. */
            subject?: string;
            /** @description Mail thread id or Slack channel id. */
            container?: string;
            /** @description Entries in the whole chain. */
            entries: number;
            /** @description How many of them the query hit. matched/entries is the honest measure of whether it is about the query. */
            matched: number;
            /**
             * @description Earliest – latest dates, e.g. '2 Jan 2026 – 14 Mar 2026'.
             * @example 2 Jan 2026 – 14 Mar 2026
             */
            span?: string;
            /** @description Which recorded query found it. */
            query: string;
        };
        /** @description Every non-2xx response carries this and nothing else. */
        Error: {
            /**
             * @description What went wrong, in the same words the CLI would use. Written to be shown to a person.
             * @example mode "semantic": no embedding daemon reachable at http://localhost:11434: start it with `ollama serve`
             */
            error: string;
        };
        /**
         * Timeline
         * @description One email trail, unspooled out of its threads and forwards into a single chronological transcript. Produced by a collector (e.g. the mail-timeline skill); consumed by the chainmail renderer.
         */
        TimelineSpec: {
            /**
             * @description Contract version. Absent means 1.
             * @default 1
             */
            specVersion: number;
            /** @description Page title. A leading # renders as a channel-style hash. */
            title: string;
            /** @description One or two sentences. Provenance belongs in queries/threads/sourceNotes, not here. */
            subtitle?: string;
            /** @description Names this collection pass, e.g. 'pass 2, 20 Aug 2026'. */
            runLabel?: string;
            /** @description Labels of every pass so far, oldest first. */
            runs?: string[];
            /**
             * @default light
             * @enum {unknown}
             */
            theme: "light" | "dark" | "auto";
            /** @default Still open */
            openItemsTitle: string;
            /** @description Unresolved questions, commitments and ownerless decisions. HTML permitted; cross-links encouraged. */
            openItems?: string[];
            /** @description Sender name -> image (data: URI or URL). Keys must match Message.sender exactly. */
            avatars?: {
                [key: string]: string;
            };
            /** @description The full cast, including people who only ever appear as recipients. */
            participants?: {
                name: string;
                org?: string;
                /** @description Omit when no address appears anywhere in the trail. Never guess one. */
                email?: string;
                role?: string;
                /** @description Use instead of role for cc-only people and aliases. */
                note?: string;
            }[];
            /** @description Selection parameters this run was invoked with, so a later refresh reproduces the same page. Only what the rest of the spec cannot already supply; never a machine-local path. */
            runParams?: {
                /** @description Addresses belonging to the reader, whose messages render as outbound. */
                me?: string[];
                /** @description How many chains the search was allowed to select. */
                limit?: number;
                /** @description Address, name or slack uid the selection was filtered to. */
                person?: string;
                /** @description YYYY-MM-DD floor on entry dates. */
                since?: string;
            };
            /** @description Searches run, so a null result is interpretable. */
            queries?: (string | {
                q: string;
                note?: string;
            })[];
            /** @description Mail threads the transcript was assembled from. */
            threads?: {
                subject?: string;
                /** @description Gmail thread or message id; links out. */
                id?: string;
                count?: number;
                span?: string;
                note?: string;
            }[];
            /** @description Provenance caveats: avatar sources, unrecoverable addresses, truncation. */
            sourceNotes?: {
                title: string;
                items: string[];
            }[];
            messages: components["schemas"]["TimelineEntry"][];
        };
        TimelineEntry: {
            /**
             * @description 'note' is a meeting or event that never existed as an email.
             * @default message
             * @enum {unknown}
             */
            kind: "message" | "note";
            /** @description Stable anchor. Omit to derive from date+time+sender; content-derived ids survive inserting entries mid-trail. */
            id?: string;
            /** @description As displayed, e.g. 'Thu 16 Jul 2026'. Not normalised. */
            date: string;
            /** @description As displayed, e.g. '11:35'. Absent for undated notes. */
            time?: string;
            /** @description The zone this entry's clock is in, e.g. 'NZST', '+0530'. Drives absolute-time ordering. Omit rather than guess: absent means the zone is unknown and the renderer shows it as unknown. */
            tz?: string;
            /**
             * @description Where tz came from. 'stated' is the source's own Date header or zone label. 'inferred' was worked out from other evidence and must be presented as a claim, not a fact. Omit when tz is absent.
             * @enum {unknown}
             */
            tzSource?: "stated" | "inferred";
            sender?: string;
            /** @description Drives colour, assigned in first-appearance order. */
            org?: string;
            fromEmail?: string;
            /** @description Free text as it appeared, including 'cc ...'. */
            to?: string;
            /** @description Names the chain when this entry opens one. Capture it during collection. */
            subject?: string;
            /** @description Notes only: what the meeting was. */
            label?: string;
            /** @description Trusted HTML. <p>, <ul>, <b>, <code>, <p class="ed"> for editorial gloss, <a class="xref"> for cross-links. */
            body: string;
            /** @description Reconstructed from quoted text; never existed as a standalone message here. */
            quoted?: boolean;
            /** @description The reader's own outbound. */
            me?: boolean;
            /** @description Where it came from: a Gmail id, or 'unspooled from the 2 Aug email'. */
            source?: string;
            gmailId?: string;
            threadId?: string;
            /** @description Id of the entry this replies to. Absent means it opens a chain. Coverage here drives ordering, lanes and the reply tree. */
            parent?: string;
            /** @description Meeting scheduling exhaust (invitation, notes, accept/decline). Forces the classification the renderer would otherwise infer. */
            meta?: boolean;
            mentions?: string[];
            attachments?: {
                name: string;
                kind?: string;
                size?: string;
                /** @description Links to the message in Gmail. Only ever present on real messages. */
                gmailId?: string;
                /** @description Opens the attachment at its source, for attachments not reached through Gmail. */
                link?: string;
                /** @description Thumbnail as a data: URI. Never a URL — the page renders without a network. */
                preview?: string;
                previewW?: number;
                previewH?: number;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search: {
        parameters: {
            query?: {
                /**
                 * @description Free text. Double-quoted runs are kept as phrases; every other term must match. Terms that look like identifiers also go to the trigram index.
                 * @example solar install quote
                 */
                q?: string;
                /**
                 * @description An address, display name or Slack uid. Matches anyone recorded on the entry, author or recipient — on a real trail a quarter of the participants appear only in to:/cc:, so "threads Ada was on" cannot be an author-only filter.
                 * @example ada@example.com
                 */
                person?: string;
                /**
                 * @description Only entries on or after this date.
                 * @example 2026-01-31
                 */
                since?: string;
                /** @description Retrieval. semantic and hybrid need vectors (`corpus embed`) AND a running local embedding daemon; without the daemon they return 503, never an empty result set. */
                mode?: "lexical" | "semantic" | "hybrid";
                /** @description How many chains (or entries) to return. */
                limit?: number;
                /** @description Return the matching entries instead of the chains they belong to. Changes which array of the response is populated. */
                entries?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked candidates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description No filter given, or a parameter could not be parsed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description mode=semantic or mode=hybrid, and the embedding daemon is not reachable or has not pulled the model. The message names the fix. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The embedding daemon did not answer in time. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    buildSpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecRequest"];
            };
        };
        responses: {
            /** @description A timeline spec, valid against schema/timeline.schema.json. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineSpec"];
                };
            };
            /** @description Malformed body, an empty chains list, or a selection that resolved to no entries. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description One of the named chains is not in the corpus. The message names which. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too many spec builds already in flight. Retry-After is set. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSavedSpec: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The name the build was saved under. Letters, digits, '.', '_', '-'; no slashes and no '..'.
                 * @example solar-install-quote
                 */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The saved timeline spec. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineSpec"];
                };
            };
            /** @description The name is not a valid spec name. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No page was ever saved under that name. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Corpus natural key, as search reports it. Percent-encode it: it contains a colon and usually angle brackets.
                 * @example mail:<c0ffee-1@example.com>
                 */
                extId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The entry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusEntry"];
                };
            };
            /** @description No entry carries that id. Distinct from a search that matched nothing, which is a 200 with an empty array. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getChain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Ext id of any entry in the chain. Percent-encode it.
                 * @example mail:<c0ffee-1@example.com>
                 */
                rootExtId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The chain in time order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainResponse"];
                };
            };
            /** @description No entry carries that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Corpus statistics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    getPeople: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description People, most involved first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeopleResponse"];
                };
            };
        };
    };
    refreshSpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description The refreshed spec and what the refresh did. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Malformed body, a spec with no messages, or a spec version this build cannot reproduce. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
