/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * One email trail, unspooled out of its threads and forwards into a single chronological transcript. Produced by a collector (e.g. the mail-timeline skill); consumed by the chainmail renderer.
 */
export interface Timeline {
  /**
   * Contract version. Absent means 1.
   */
  specVersion?: number;
  /**
   * Page title. A leading # renders as a channel-style hash.
   */
  title: string;
  /**
   * One or two sentences. Provenance belongs in queries/threads/sourceNotes, not here.
   */
  subtitle?: string;
  /**
   * Names this collection pass, e.g. 'pass 2, 20 Aug 2026'.
   */
  runLabel?: string;
  /**
   * Labels of every pass so far, oldest first.
   */
  runs?: string[];
  theme?: "light" | "dark" | "auto";
  openItemsTitle?: string;
  /**
   * Unresolved questions, commitments and ownerless decisions. HTML permitted; cross-links encouraged.
   */
  openItems?: string[];
  /**
   * Sender name -> image (data: URI or URL). Keys must match Message.sender exactly.
   */
  avatars?: {
    [k: string]: string;
  };
  /**
   * The full cast, including people who only ever appear as recipients.
   */
  participants?: {
    name: string;
    org?: string;
    /**
     * Omit when no address appears anywhere in the trail. Never guess one.
     */
    email?: string;
    role?: string;
    /**
     * Use instead of role for cc-only people and aliases.
     */
    note?: string;
  }[];
  /**
   * Selection parameters this run was invoked with, so a later refresh reproduces the same page. Only what the rest of the spec cannot already supply; never a machine-local path.
   */
  runParams?: {
    /**
     * Addresses belonging to the reader, whose messages render as outbound.
     */
    me?: string[];
    /**
     * How many chains the search was allowed to select.
     */
    limit?: number;
    /**
     * Address, name or slack uid the selection was filtered to.
     */
    person?: string;
    /**
     * YYYY-MM-DD floor on entry dates.
     */
    since?: string;
  };
  /**
   * Searches run, so a null result is interpretable.
   */
  queries?: (
    | string
    | {
        q: string;
        note?: string;
      }
  )[];
  /**
   * Mail threads the transcript was assembled from.
   */
  threads?: {
    subject?: string;
    /**
     * Gmail thread or message id; links out.
     */
    id?: string;
    count?: number;
    span?: string;
    note?: string;
  }[];
  /**
   * Provenance caveats: avatar sources, unrecoverable addresses, truncation.
   */
  sourceNotes?: {
    title: string;
    items: string[];
  }[];
  /**
   * @minItems 1
   */
  messages: [Entry, ...Entry[]];
}
export interface Entry {
  /**
   * 'note' is a meeting or event that never existed as an email.
   */
  kind?: "message" | "note";
  /**
   * Stable anchor. Omit to derive from date+time+sender; content-derived ids survive inserting entries mid-trail.
   */
  id?: string;
  /**
   * As displayed, e.g. 'Thu 16 Jul 2026'. Not normalised.
   */
  date: string;
  /**
   * As displayed, e.g. '11:35'. Absent for undated notes.
   */
  time?: string;
  /**
   * The zone this entry's clock is in, e.g. 'NZST', '+0530'. Drives absolute-time ordering. Omit rather than guess: absent means the zone is unknown and the renderer shows it as unknown.
   */
  tz?: string;
  /**
   * Where tz came from. 'stated' is the source's own Date header or zone label. 'inferred' was worked out from other evidence and must be presented as a claim, not a fact. Omit when tz is absent.
   */
  tzSource?: "stated" | "inferred";
  sender?: string;
  /**
   * Drives colour, assigned in first-appearance order.
   */
  org?: string;
  fromEmail?: string;
  /**
   * Free text as it appeared, including 'cc ...'.
   */
  to?: string;
  /**
   * Names the chain when this entry opens one. Capture it during collection.
   */
  subject?: string;
  /**
   * Notes only: what the meeting was.
   */
  label?: string;
  /**
   * Trusted HTML. <p>, <ul>, <b>, <code>, <p class="ed"> for editorial gloss, <a class="xref"> for cross-links.
   */
  body: string;
  /**
   * Reconstructed from quoted text; never existed as a standalone message here.
   */
  quoted?: boolean;
  /**
   * The reader's own outbound.
   */
  me?: boolean;
  /**
   * Where it came from: a Gmail id, or 'unspooled from the 2 Aug email'.
   */
  source?: string;
  gmailId?: string;
  threadId?: string;
  /**
   * Id of the entry this replies to. Absent means it opens a chain. Coverage here drives ordering, lanes and the reply tree.
   */
  parent?: string;
  /**
   * Meeting scheduling exhaust (invitation, notes, accept/decline). Forces the classification the renderer would otherwise infer.
   */
  meta?: boolean;
  mentions?: string[];
  attachments?: {
    name: string;
    kind?: string;
    size?: string;
    /**
     * Links to the message in Gmail. Only ever present on real messages.
     */
    gmailId?: string;
    /**
     * Opens the attachment at its source, for attachments not reached through Gmail.
     */
    link?: string;
    /**
     * Thumbnail as a data: URI. Never a URL — the page renders without a network.
     */
    preview?: string;
    previewW?: number;
    previewH?: number;
  }[];
}
