/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * One email trail, unspooled out of its threads and forwards into a single chronological transcript. Produced by a collector (e.g. the mail-timeline skill); consumed by the chainmail renderer. The fields that carry HTML (body, subtitle, openItems) are rendered as authored, so a spec from an untrusted source must be sanitised before it is rendered.
 */
export interface Timeline {
  /**
   * Contract version. Absent means 1.
   */
  specVersion?: number;
  /**
   * Page title. A leading # renders as a channel-style hash.
   */
  title: string;
  /**
   * One or two sentences. Provenance belongs in queries/threads/sourceNotes, not here. Rendered as authored (inline <em>, <b>, <code>, <a> with an http(s) or #fragment href); a spec from an untrusted source must be sanitised before rendering.
   */
  subtitle?: string;
  /**
   * Names this collection pass, e.g. 'pass 2, 20 Aug 2026'.
   */
  runLabel?: string;
  /**
   * Labels of every pass so far, oldest first.
   */
  runs?: string[];
  /**
   * Renderer theme. Omitted means the renderer's default (light).
   */
  theme?: "light" | "dark" | "auto";
  /**
   * Heading over the unresolved-questions section. Omitted means 'Still open'.
   */
  openItemsTitle?: string;
  /**
   * Unresolved questions, commitments and ownerless decisions. HTML from the subtitle allowlist: inline <em>, <b>, <code>, <a> with an http(s) or #fragment href. A spec from an untrusted source must be sanitised before rendering.
   */
  openItems?: string[];
  /**
   * Sender name -> image. Only a data: image URI or an http(s) URL is rendered — the renderer refuses anything else. Keys must match Message.sender exactly.
   */
  avatars?: {
    [k: string]: string;
  };
  /**
   * The full cast, including people who only ever appear as recipients.
   */
  participants?: {
    name: string;
    org?: string;
    /**
     * Omit when no address appears anywhere in the trail. Never guess one.
     */
    email?: string;
    role?: string;
    /**
     * Use instead of role for cc-only people and aliases.
     */
    note?: string;
  }[];
  /**
   * Selection parameters this run was invoked with, so a later refresh reproduces the same page. Only what the rest of the spec cannot already supply; never a machine-local path.
   */
  runParams?: {
    /**
     * Addresses belonging to the reader, whose messages render as outbound.
     */
    me?: string[];
    /**
     * How many chains the search was allowed to select.
     */
    limit?: number;
    /**
     * Address, name or slack uid the selection was filtered to.
     */
    person?: string;
    /**
     * YYYY-MM-DD floor on entry dates.
     */
    since?: string;
  };
  /**
   * Searches run, so a null result is interpretable.
   */
  queries?: (
    | string
    | {
        q: string;
        note?: string;
      }
  )[];
  /**
   * Mail threads the transcript was assembled from.
   */
  threads?: {
    subject?: string;
    /**
     * Gmail thread or message id; links out.
     */
    id?: string;
    count?: number;
    span?: string;
    note?: string;
  }[];
  /**
   * Provenance caveats: avatar sources, unrecoverable addresses, truncation.
   */
  sourceNotes?: {
    title: string;
    items: string[];
  }[];
  /**
   * @minItems 1
   */
  messages: [Entry, ...Entry[]];
}
export interface Entry {
  /**
   * 'note' is a meeting or event that never existed as an email. Omitted means message.
   */
  kind?: "message" | "note";
  /**
   * Stable anchor. Omit to derive from date+time+sender; content-derived ids survive inserting entries mid-trail.
   */
  id?: string;
  /**
   * As displayed, e.g. 'Thu 16 Jul 2026'. Not normalised.
   */
  date: string;
  /**
   * As displayed, e.g. '11:35'. Absent for undated notes.
   */
  time?: string;
  /**
   * The zone this entry's clock is in, e.g. 'NZST', '+0530'. Drives absolute-time ordering. Omit rather than guess: absent means the zone is unknown and the renderer shows it as unknown.
   */
  tz?: string;
  /**
   * Where tz came from. 'stated' is the source's own Date header or zone label. 'inferred' was worked out from other evidence and must be presented as a claim, not a fact. Omit when tz is absent.
   */
  tzSource?: "stated" | "inferred";
  sender?: string;
  /**
   * Drives colour, assigned in first-appearance order.
   */
  org?: string;
  fromEmail?: string;
  /**
   * Free text as it appeared, including 'cc ...'.
   */
  to?: string;
  /**
   * Names the chain when this entry opens one. Capture it during collection.
   */
  subject?: string;
  /**
   * Notes only: what the meeting was.
   */
  label?: string;
  /**
   * Rendered HTML, produced through the collector's allowlist (internal/spec/sanitise.go): blocks <p>, <div>, <blockquote>, <ul>/<ol>/<li>, <table>/<tr>/<td>/<th>, <pre>, <h1>-<h6>, <hr>; inline <a href> (http(s) only), <img src> (http(s) or data:image only), <b>, <i>, <em>, <strong>, <u>, <s>, <code>, <span style>; the editorial gloss (<p class="ed">) and the signature fold (<details class="sig">, <summary title>, <div class="sigbd">). Nothing else — no scripts, stylesheets, event handlers or other URL schemes. The collector enforces this; a spec that did not come from the collector is only as safe as its author, so sanitise an untrusted spec before rendering.
   */
  body: string;
  /**
   * Reconstructed from quoted text; never existed as a standalone message here.
   */
  quoted?: boolean;
  /**
   * The reader's own outbound.
   */
  me?: boolean;
  /**
   * Where it came from: a Gmail id, or 'unspooled from the 2 Aug email'.
   */
  source?: string;
  gmailId?: string;
  threadId?: string;
  /**
   * Id of the entry this replies to. Absent means it opens a chain. Coverage here drives ordering, lanes and the reply tree.
   */
  parent?: string;
  /**
   * A quoter's in-place change to a message it quoted (issue #42). Each names the base that was edited, who made the change (the quoter), when, and the quoter's modified text. The renderer draws these inline inside this message instead of floating the derived copy as its own node.
   */
  edits?: {
    /**
     * Spec id of the derived (edited) copy; the diff source.
     */
    id?: string;
    /**
     * Spec id of the original message the change was made to.
     */
    base?: string;
    /**
     * The quoter who made the edit.
     */
    who?: string;
    /**
     * When the quoting message was sent, e.g. '14:00'.
     */
    time?: string;
    /**
     * The quoter's modified text of the quote, as stored (plain text, not HTML).
     */
    body?: string;
  }[];
  /**
   * Meeting scheduling exhaust (invitation, notes, accept/decline). Forces the classification the renderer would otherwise infer.
   */
  meta?: boolean;
  mentions?: string[];
  attachments?: {
    name: string;
    kind?: string;
    size?: string;
    /**
     * Links to the message in Gmail. Only ever present on real messages.
     */
    gmailId?: string;
    /**
     * Opens the attachment at its source, for attachments not reached through Gmail.
     */
    link?: string;
    /**
     * Thumbnail as a data: URI. Never a URL — the page renders without a network.
     */
    preview?: string;
    previewW?: number;
    previewH?: number;
  }[];
}
